version: '2'
services:
  bicicletasdb:
    image: mysql:5.7.22
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: diego
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: bicicletasdb
      MYSQL_HOST: bicicletasdb
  biciun:
    image: fullhd4knofake/bicicletas
    # build: .
    ports:
      - "3004:9002"
    depends_on:
      - bicicletasdb